import React from 'react';

export const Data =(
    () => [
      {
        ScouterInitials: '',
        TeamNumber: 2442,
        MatchNumber: 2,
        AllianceColor: '',
        AutoLowMade: 0,
        AutoLowMissed: 0,
        AutoHighMade: 0,
        AutoHighMissed: 0,
        Taxi: 'false',
        AutoPlacement: 0,
        TeleLowMade: 0,
        TeleLowMissed: 0,
        TeleUpperMade: 6,
        TeleUpperMissed: 15,
        Hangar: '',
        LaunchpadUse: false,
        NumberOfFouls: 0,
        NumberOfTech: 0,
        YellowCard: false,
        RedCard: false,
        Disabled: false,
        Disqualified: false,
        HangarBonus: false,
        CargoBonus: false, 
        NumberOfRankingPoints: 0,
        Strategy: '',
        Comment: '',
        OpinionScale: 0
      },
      {
        ScouterInitials: 'SF',
        TeamNumber: 505,
        MatchNumber: 2,
        AllianceColor: 'RED',
        AutoLowMade: 0,
        AutoLowMissed: 0,
        AutoHighMade: 0,
        AutoHighMissed: 0,
        Taxi: 'false',
        AutoPlacement: 0,
        TeleLowMade: 0,
        TeleLowMissed: 0,
        TeleUpperMade: 6,
        TeleUpperMissed: 15,
        Hangar: '',
        LaunchpadUse: false,
        NumberOfFouls: 0,
        NumberOfTech: 0,
        YellowCard: false,
        RedCard: false,
        Disabled: false,
        Disqualified: false,
        HangarBonus: false,
        CargoBonus: false, 
        NumberOfRankingPoints: 0,
        Strategy: '',
        Comment: '',
        OpinionScale: 0
      },
      {
        ScouterInitials: 'BB',
        TeamNumber: 88,
        MatchNumber: 2,
        AllianceColor: 'BLUE',
        AutoLowMade: 0,
        AutoLowMissed: 0,
        AutoHighMade: 0,
        AutoHighMissed: 0,
        Taxi: 'false',
        AutoPlacement: 0,
        TeleLowMade: 0,
        TeleLowMissed: 0,
        TeleUpperMade: 6,
        TeleUpperMissed: 15,
        Hangar: '',
        LaunchpadUse: false,
        NumberOfFouls: 0,
        NumberOfTech: 0,
        YellowCard: false,
        RedCard: false,
        Disabled: false,
        Disqualified: false,
        HangarBonus: false,
        CargoBonus: false, 
        NumberOfRankingPoints: 0,
        Strategy: '',
        Comment: '',
        OpinionScale: 0
      },
    ],
    []
  )